version: '3'
services:
  app:
    build: .
    container_name: app
    networks:
     - my-net
    ports:
     - "80:8080"
    environment:
     - MAIL_HOST=mailhog
    depends_on:
     - mailhog
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    networks:
     - my-net
    ports:
     - "8025:8025"
networks:
  my-net:
    driver: bridge
